spring.datasource.url=jdbc:postgresql://localhost:5432/service_app
spring.datasource.username=postgres
spring.datasource.password=Qweas@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true